export const { VITE_KAKAO_REST_KEY, VITE_KAKAO_REDIRECT_URI } = import.meta.env;
export const {
  VITE_GOOGLE_REST_KEY,
  VITE_GOOGLE_CLIENT_ID,
  VITE_GOOGLE_CLIENT_SECRET,
  VITE_GOOGLE_REDIRECT_URI,
} = import.meta.env;
export const {
  VITE_NAVER_CLIENT_ID,
  VITE_NAVER_CLIENT_SECRET,
  VITE_NAVER_REDIRECT_URI,
} = import.meta.env;
